/**:
  ros__parameters:
    debug: true
    target_frame: odom
    detect_color: 1 # 0: blue, 1: red
    binary_thres: 80

    use_pca: true # 使用PCA算法矫正灯条的角点
    use_ba: true # 使用BA优化算法求解装甲板的Yaw角 

    light.min_ratio: 0.02
    light.max_ratio: 5.0
    light.max_angle: 80.0
    light.color_diff_thresh: 15

    armor.min_light_ratio: 0.2
    armor.min_small_center_distance: 0.2
    armor.max_small_center_distance: 3.2
    armor.min_large_center_distance: 3.6
    armor.max_large_center_distance: 9.0
    armor.max_angle: 65.0

    classifier_threshold: 0.05
    ignore_classes: ["negative"]